name: cpp-cmake-mingw-prebuilt-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      targetZip: fnmatch.js-${{ github.ref_name }}-emscripten.zip
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/checkout@v4
        with:
          path: '../../${{ github.event.repository.name }}'
      
      - name: Build
        run: |
          docker run \
          --rm \
          -v $(pwd):/src \
          -u $(id -u):$(id -g) \
          emscripten/emsdk \
          emcc -lembind -o fnmatch.js main.cpp

      - run: cp -f 'fnmatch.js' '$HOME/${{ github.event.repository.name }}'
          
      - run: cp -f 'fnmatch.wasm' '$HOME/${{ github.event.repository.name }}'
          
      - run: cp -f 'index.html' '$HOME/${{ github.event.repository.name }}'
      
      - run: ls
        
      - working-directory: '$HOME/${{ github.event.repository.name }}'
        run: ls
        
      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          cwd: '$HOME/${{ github.event.repository.name }}'
          # The arguments for the `git add` command (see the paragraph below for more info)
          # Default: '.'
          # add: '["fnmatch.js", "fnmatch.wasm", "index.html"]'
          
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          path: |
            fnmatch.js
            fnmatch.wasm
            index.html
          filename: "${{ env.targetZip }}"

      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.targetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
